services:
  postgres:
    image: postgres:15-alpine
    container_name: encaixa_postgres
    environment:
      POSTGRES_DB: encaixa
      POSTGRES_USER: encaixa_user
      POSTGRES_PASSWORD: encaixa_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - encaixa_net

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.7
    container_name: encaixa_keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev --import-realm
    volumes:
      - ./docker/keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    ports:
      - "8080:8080"
    networks:
      - encaixa_net

volumes:
  postgres_data:

networks:
  encaixa_net:
    driver: bridge

